apiVersion: v1
kind: Service
metadata:
  name: dfs-metadata
  namespace: {{ .Values.global.namespace }}
  labels:
    app: dfs-metadata
    component: master
    app.kubernetes.io/name: dfs-metadata
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.metadata.service.type }}
  ports:
  - port: {{ .Values.metadata.service.port }}
    targetPort: {{ .Values.metadata.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    app: dfs-metadata
