{{- if .Values.prometheus.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dfs-prometheus
  namespace: {{ .Values.global.namespace }}
  labels:
    app: dfs-prometheus
    app.kubernetes.io/name: dfs-prometheus
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dfs-prometheus
  template:
    metadata:
      labels:
        app: dfs-prometheus
    spec:
      serviceAccountName: dfs-prometheus
      containers:
      - name: prometheus
        image: "{{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}"
        imagePullPolicy: {{ .Values.prometheus.image.pullPolicy }}
        args:
          - '--config.file=/etc/prometheus/prometheus.yml'
          - '--storage.tsdb.path=/prometheus'
          - '--storage.tsdb.retention.time={{ .Values.prometheus.retention }}'
          - '--web.console.libraries=/usr/share/prometheus/console_libraries'
          - '--web.console.templates=/usr/share/prometheus/consoles'
        ports:
        - name: http
          containerPort: 9090
          protocol: TCP
        resources:
          {{- toYaml .Values.prometheus.resources | nindent 10 }}
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus
        - name: storage
          mountPath: /prometheus
      volumes:
      - name: config
        configMap:
          name: dfs-prometheus-config
      - name: storage
        {{- if .Values.prometheus.persistence.enabled }}
        persistentVolumeClaim:
          claimName: dfs-prometheus-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}
{{- end }}
